config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources "principales"
  get "quiz/preg1"
  post "quiz/resp1"
  get "quiz/preg2"
  post "quiz/resp2"
  get "quiz/preg3"
  post "quiz/resp3"
  get "quiz/preg4"
  post "quiz/resp4"
  get "quiz/c1"
  post "quiz/rc1"
  get "quiz/rc1"
  get "quiz/c2"
  post "quiz/rc2"
  get "quiz/rc2"
  get "quiz/c3"
  post "quiz/rc3"
  get "quiz/rc3"
  post "quiz/evalua1"
  get "quiz/evalua1"
  get "quiz/resultados"
  get "quiz/inicio"
  post "quiz/actualiza"

  root "quiz#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/principales_controller.rb
class PrincipalesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :varios, only: [:show]
  before_action :opciones, only: [:index]
  before_action :q2, only: [:show]
  def index
  #  @search = User.where("name LIKE ?","%#{params[:searchbox]}%").where(admin: nil)
  #  @per_page = params[:per_page] || 10
    @users = User.joins('LEFT JOIN resps on resps.user_id = users.id').where(admin: nil).distinct
    #@users = @search.joins('LEFT JOIN resps on resps.user_id = users.id').distinct.paginate(page: params[:page], per_page: @per_page)
    @usuarios = User.joins('LEFT JOIN resps on resps.user_id = users.id').where(admin: nil).distinct
    respond_to do |format|
    format.html
    format.csv #{ send_data @usuarios.to_csv }
    format.xls # { send_data @products.to_csv(col_sep: "\t") }
  end

 end

 def show
   if Resp.exists?(user_id: params[:id])
     @datos=Resp.where(user_id: params[:id])
     @donde=@datos.first
     @ss=@donde.res
     @user= User.find(params[:id])
     @opc = true
   else
     @opc= false
   end
 end


 def varios
   @respuestas = ["Economy","International Relationships","International Security","Society","Enviroment/Health","International Justice","Technology"]
   @idr = ["ilo","who","sc","uni","fao","icc","cst"]
   @titulo1 = ["International Labor Organization (ILO)",
   "World Health Organization (WHO)","Security Council (SC)",
   "United Nations International Children´s Emergency Fund (UNICEF)",
 "Food and Agriculture Organization of the United Nations (FAO)",
"International Criminal Court (ICC)","Commission on Science and Technology for Development (CSTD)"]
   @sub1 = ["Unemployment Caused by Artificial Intelligence",
   "Prevention of Mosquitoe Proliferation to Fight Mosquitoe-Born Diseases","Kurdish Conflict",
 "Education for Children with Disabilities","Administration of Alimentary Resources",
"Against Lyndon B. Johnson for the Acts of Wars Committed in The Operation Ranch Hand",
"Superbug Relentless Threat"]
   @quien1 = ["Daniel Contreras, Alan Aguilar, Pablo Alduncin",
     "Monserrat Barrientos, Jorge Tenorio, Melanie León","Paola Solís, José Diego Romero, Jesús Daniel",
   "Daniela Villa Lombardero, José Bulnes Martínez, Regina Peredo","María José Alejo Flores, Valeria Lorena Cano Echeverría",
 "","María José Campos, Amanda Polcaqui, Miguel Jiménez "]

   @level1 = ["Standard","Standard","Standard","Introductory","Introductory","Standard","Standard"]
   @grade1 = ["High School","High School","High School","Middle High School","Middle High School","High School","High School"]
   @url1 = ["https://damunapp.wordpress.com/2016/06/07/international-labour-organization-ilo/",
     "https://damunapp.wordpress.com/2016/06/07/economic-and-social-council-ecosoc/","https://damunapp.wordpress.com/2016/06/07/","https://damunapp.wordpress.com/2016/06/07/united-nations-international-childrens-emergency-fund-unicef/",
     "https://damunapp.wordpress.com/2016/06/07/world-health-organization-who/",
     "https://damunapp.wordpress.com/2016/06/07/international-court-of-justice-icj/",
     "https://damunapp.wordpress.com/2016/06/07/commission-on-science-and-technology-for-development-cstd/"
   ]
 end

 def q2
   @cual = ["Econ","IR","IS","Soc","Env","IJ","Tec"]
   @imagen = ["ilo","ga","hsc","sc","unep","ecosoc","unodc","crisis","esc","who","icc","cstd","cct","cpi","glam","fao","uni","hrc"]
   @titulo = ["International Labour Organization (ILO)","General Assembly (GA)","Historical Security Council (HSC)","Security Council (SC)","United Nations Environment Programme (UNEP)",
   "Economic and Social Council (ECOSOC)","United Nations Office on Drugs and Crime (UNODC)","CRISIS","Emergency Security Council (ESC)","World Health Organization (WHO)","International Criminal Court (ICC)",
 "Commission on Science and Technology for Development (CSTD)","Comité Contra el Terrorismo (CCT)","Corte Penal Internacional (CPI)","Gabinete Legal y Ampliado Mexicano (GLAM)",
"Food and Agriculture Organization of the United Nations (FAO)","United Nations International Children’s Emergency Fund (UNICEF)","Human Rights Council (HRC)"]
   @sub = ["Unemployment Caused by Artificial Intelligence","Intervention in Emerging Countries","Third Arab Israeli War","Kurdish Conflict","Air Pollution in Cosmopolitan Cities",
   "Global Refugee Immigration Overload","Cyber Terrorism: Internet as a Tool for Terrorist Attacks","Secret Topic","Secret Topic","Prevention of Mosquitoe Proliferation to Fight Mosquitoe-Born Diseases",
 "Against Lyndon B. Johnson for the Acts of Wars Committed in The Operation Ranch Hand","Superbug Relentless Threat",
 "Régimen Talibán en Afganistán","Corte Penal Internacional (CPI)","Llegada de Petróleo Extranjero a México","Administration of Alimentary Resources","Education for Children with Disabilities","Human Trafficking for forced labor
purposes"]
   @quien = ["Daniel Contreras, Alan Aguilar, Pablo Alduncin","Silvana Inés Rodal Fregoso, Victoria María Ostrowski López","Francisco Morales, Emiliano Quiñonez","Paola Solís, José Diego Romero, Jesús Daniel",
   "Vicente Tolama Paisano, Juan Pablo Castillo Mendoza, Sofía Ramírez Gross","Ana Paola Prado, Metzery Celaya, Markova Lozano","Ana Elisa López, Mauricio Tenorio, Javier Rischtl",
 "Andrés Lappe, Daniela Rojo","Camila Valdivieso, Andrea Rossano, Ana Paola Roanova","Monserrat Barrientos, Jorge Tenorio, Melanie León","Julio Morales, Maximiliano Lopezlarssen, Jessica Adame",
 "María José Campos, Amanda Polcaqui, Miguel Jiménez","Andrea López, Ian Valdovinos, Arantza Martínez","Roberto André Osornio Villareal, Carlos Rincón Castell, Jorge Augusto Tavera Manzanilla","Ruben Bringas, Luis Enrique de la Concha, Alejandro Vargas",
"María José Alejo Flores, Valeria Lorena Cano Echeverría","Daniela Villa Lombardero, José Bulnes Martínez, Regina Peredo","Heinz Hermann Wendler Alfaro, Angela Sofia Crocker Sanchez, Alexa Orive
Coronel"]
   @level = ["Standard","Advanced","Standard","Standard","Standard","Advanced","Standard","Advanced","Advanced","Standard","Standard","Standard","Estandar","Estandar","Estandar","Introductory","Introductory","Standard"]
   @grade = ["High School","High School","High School","High School","High School","High School","High School","High School (No pairs allowed)","High School (No pairs allowed)","High School (No pairs allowed)",
     "High School (No pairs allowed)","High School (No pairs allowed)","Secundaria (No se permiten parejas)","Bachillerato","Bachillerato","Middle School","Middle High School"," Middle School (No pairs allowed)"]
   @url = ["https://damunapp.wordpress.com/2016/06/07/international-labour-organization-ilo/","https://damunapp.wordpress.com/2016/06/12/general-assembly-ga/",
   "https://damunapp.wordpress.com/2016/06/07/historical-security-council-hsc/","https://damunapp.wordpress.com/2016/06/07/","https://damunapp.wordpress.com/2016/06/07/united-nations-environment-programme-unep/",
 "https://damunapp.wordpress.com/2016/06/07/economic-and-social-council-ecosoc/","https://damunapp.wordpress.com/2016/06/07/united-nations-office-on-drugs-and-crime-unodc/","https://damunapp.wordpress.com/2016/06/07/",
 "https://damunapp.wordpress.com/2016/06/07/emergency-security-council-ega/","https://damunapp.wordpress.com/2016/06/07/economic-and-social-council-ecosoc/","https://damunapp.wordpress.com/2016/06/07/international-court-of-justice-icj/",
 "https://damunapp.wordpress.com/2016/06/07/commission-on-science-and-technology-for-development-cstd/","https://damunapp.wordpress.com/2016/06/07/food-and-agriculture-organization-of-the-united-nations-fao/",
 "https://damunapp.wordpress.com/2016/06/07/international-criminal-court-icc/","https://damunapp.wordpress.com/2016/06/07/ctc-2/"]
 end


 def opciones
   @indice=[['1',1],['2',2],['3',3]]
 end

end

app/helpers/principales_helper.rb
module PrincipalesHelper
end

app/views/principales/index.csv.erb
<% headers = ["Nombre", "Correo","Realizado","Comite(s)"] %>
<%= CSV.generate_line headers %>
<% @usuarios.each do |user| %>
<% @valores="" %>
<% Resp.where(user_id: user.id).each do |r| %>
<% @valores=@valores+r.cual.to_s+"," %>
<% end %>
<% if @resp = Resp.find_by(user_id: user.id) %>
<% row = [ user.name+" "+user.paterno+" "+user.materno , user.email, @resp.created_at.strftime('%b %d, %Y , %I:%M %p'), @valores] %>
<% else %>
<% row = [ user.name+" "+user.paterno+" "+user.materno , user.email, "No"] %>
<% end %>
<%= CSV.generate_line row %>
<% end %>

app/views/principales/index.html.erb
<% if user_signed_in? %>
<% if current_user.admin!=1 %>
<% controller.redirect_to "public/404.html" %>
<% else %>

<div class="panel panel-default">
  <div class="panel-heading">Usuarios registrados</div>
<br>

<br><br>
<div class="table-responsive">
  <table id="example2" class="table">
    <thead><tr>
<th>Usuario</th>
<th>Correo</th>
<th>Edad</th>
<th>Escuela</th>
<th>Grado</th>
<th>Respuestas</th>
<th>Estado cuestionario</th>
</tr></thead><tbody>
<% @t = Time.now %>
<% @añoactual = @t.strftime("%Y").to_i %>
    <% @users.each do |user| %>
    <tr>
      <% if @resp = Resp.find_by(user_id: user.id) %>
      <td><%= user.name %> <%= user.paterno %> <%= user.materno %><rt></td>
      <td><%= user.email %></td>
      <td><%= @añoactual-user.edad.strftime("%Y").to_i %></td>
      <td><%= user.escuela %></td>
      <% if user.grado == nil %>
      <td>Sin grado</td>
      <% elsif user.grado == "1" %>
      <td>1ro de Secundaria</td>
      <% elsif user.grado == "2" %>
      <td>2ndo de Secundaria</td>
      <% elsif user.grado == "3" %>
      <td>3ro de Secundaria</td>
      <% elsif user.grado == "4" %>
      <td>1ro de Preparatoria</td>
      <% elsif user.grado == "5" %>
      <td>2ndo de Preparatoria</td>
      <% elsif user.grado == "6" %>
      <td>3ro de Preparatoria</td>
      <% end %>
      <% @valores="" %>
      <% Resp.where(user_id: user.id).each do |r| %>
      <% @valores=@valores+r.cual.to_s+"\n" %>
      <% end %>
      <td><%= @valores %></td>
      <td>Realizada el <%= @resp.created_at.strftime('%b %d, %Y , %I:%M %p') %></td>
      <td><%= link_to "Resultados", principale_path(user) %></td>
      <% else %>
      <td><%= user.name %> <%= user.paterno %> <%= user.materno %></td>
      <td><%= user.email %></td>
      <td><%= @añoactual-user.edad.strftime("%Y").to_i %></td>
      <td><%= user.escuela %></td>
      <% if user.grado == nil %>
      <td>Sin grado</td>
      <% elsif user.grado == "1" %>
      <td>1ro de Secundaria</td>
      <% elsif user.grado == "2" %>
      <td>2ndo de Secundaria</td>
      <% elsif user.grado == "3" %>
      <td>3ro de Secundaria</td>
      <% elsif user.grado == "4" %>
      <td>1ro de Preparatoria</td>
      <% elsif user.grado == "5" %>
      <td>2ndo de Preparatoria</td>
      <% elsif user.grado == "6" %>
      <td>3ro de Preparatoria</td>
      <% end %>
      <td>Sin respuesta</td>
      <td>Aun no ha realizado la encuesta</td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
    </table>
    <script>
          $('#example2').DataTable();
          </script>
  </div>
</div><br>

<div class="mipanel">
<p>
  Descargar:
  <%= link_to "CSV", principales_path(format: "csv") %> |
  <%= link_to "Excel", principales_path(format: "xls") %>
</p>
</div>

<% end %>

<% else %>
<% controller.redirect_to root_path %>
<% end %>

app/views/principales/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">Correo</Data></Cell>
        <Cell><Data ss:Type="String">Grado</Data></Cell>
        <Cell><Data ss:Type="String">Realizada</Data></Cell>
        <Cell><Data ss:Type="String">Comite(s)</Data></Cell>
      </Row>
    <% @usuarios.each do |user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= user.name %> <%= user.paterno %> <%= user.materno %> </Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <% if user.grado == nil %>
        <Cell><Data ss:Type="String">Sin grado</Data></Cell>
        <% elsif user.grado == "1" %>
        <Cell><Data ss:Type="String">1ro de Secundaria</Data></Cell>
        <% elsif user.grado == "2" %>
        <Cell><Data ss:Type="String">2ndo de Secundaria</Data></Cell>
        <% elsif user.grado == "3" %>
        <Cell><Data ss:Type="String">3ro de Secundaria</Data></Cell>
        <% elsif user.grado == "4" %>
        <Cell><Data ss:Type="String">1ro de Preparatoria</Data></Cell>
        <% elsif user.grado == "5" %>
        <Cell><Data ss:Type="String">2ndo de Preparatoria</Data></Cell>
        <% elsif user.grado == "6" %>
        <Cell><Data ss:Type="String">3ro de Preparatoria</Data></Cell>
        <% end %>

        <% if @resp = Resp.find_by(user_id: user.id) %>
        <Cell><Data ss:Type="String"><%= @resp.created_at.strftime('%b %d, %Y , %I:%M %p') %></Data></Cell>
        <% Resp.where(user_id: user.id).each do |r| %>
        <Cell><Data ss:Type="String"><%= r.cual.upcase %></Data></Cell>
        <% end %>
        <% else %>
        <Cell><Data ss:Type="String">No</Data></Cell>
        <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/principales/show.html.erb
<% if current_user.admin!=1 %>
<% controller.redirect_to "public/404.html" %>
<% else %>
<% if user_signed_in? %>
  <% if @opc && @ss=="2"%>
  <div class="total">
  <center><strong><p>Los comités en los cuales pertenece<br><%= @user.name%> <%= @user.paterno%> <%= @user.materno%> son:</p></strong></center>
  </div><br><br>
    <%= render "quiz/result2" %>
    <div class="mipanel"><button class="btn btn-primary" onclick="window.location.href='../'">Aceptar</button></center>
    <%= link_to "Descargar PDF", principale_path(@user, :format => 'pdf'), class: "btn btn-primary", :target => "_blank" %></div>

  <% elsif @opc && @ss=="1"%>
  <div class="total">
  <center><strong><p>Los comités en los cuales pertenece<br><%= @user.name%> <%= @user.paterno%> <%= @user.materno%> son:</p></strong></center>
  </div><br><br>
<%= render "quiz/resul" %>
<div class="mipanel"><button class="btn btn-primary" onclick="window.location.href='../'">Aceptar</button></center>
<%= link_to "Descargar PDF", principale_path(@user, :format => 'pdf'), class: "btn btn-primary" , :target => "_blank"%></div>

<% end %>
<% end %>
<% end %>