config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources "principales"
  get "quiz/preg1"
  post "quiz/resp1"
  get "quiz/preg2"
  post "quiz/resp2"
  get "quiz/preg3"
  post "quiz/resp3"
  get "quiz/preg4"
  post "quiz/resp4"
  get "quiz/c1"
  post "quiz/rc1"
  get "quiz/rc1"
  get "quiz/c2"
  post "quiz/rc2"
  get "quiz/rc2"
  get "quiz/c3"
  post "quiz/rc3"
  get "quiz/rc3"
  post "quiz/evalua1"
  get "quiz/evalua1"
  get "quiz/resultados"
  get "quiz/inicio"
  post "quiz/actualiza"

  root "quiz#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">
        <%=image_tag("ind.jpeg", alt: "Example Image", style: "max-width:60px; margin-top: -7px;")%>
    </a>
      <%= link_to "Intelligence Department", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <% if current_user.admin==1 %>
        <% else %>
        <% if Resp.where(user_id: current_user).first %>
        <li><%= link_to "Mis resultados  ", quiz_resultados_path, style: "color:white;"%></li>
        <% else %>
        <li><%= link_to "Cuestionario  ", quiz_inicio_path, style: "color:white;"%></li>
        <% end %>
        <% end %>
         <li><%= link_to "Mi cuenta  ", edit_user_registration_path, style: "color:white;"%></li>
          <li><%= link_to "Salir", destroy_user_session_path , method: :delete, style: "color:white;"%></li>
        <% else %>
          <li><%= link_to "Registrarse  ", new_user_registration_path, style: "color:white;"%></li>
          <li><%= link_to "Iniciar sesion", new_user_session_path, style: "color:white;"%></li>
        <% end %>
      </ul>



    </div>


  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Intelligence Department/ Departamento de Inteligencia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  <div class="container2">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
  </div>
    <div class="container">
  <%= yield %>
</div>
  </body>
</html>